openapi: 3.0.0
info:
  description: |
    Rust Web App API
  version: 0.0.0
  title: Rust Web App OpenAPI
tags:
  - name: user
    description: CRUD Users.
paths:
  /user:
    put:
      tags: [user]
      operationId: userPut
      summary: upsert user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IUserDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IUserDTO'
    get:
      tags: [user]
      summary: get user
      operationId: userGet
      parameters:
        - in: query
          name: userId
          schema:
            type: string
            format: uuid
          description: the ID of the user to get.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IUserDTO'
        '404':
          description: Not Found
    delete:
      tags: [user]
      summary: delete user
      operationId: userDelete
      parameters:
        - in: query
          name: userId
          schema:
            type: string
            format: uuid
          description: The ID of the user to delete.
      responses:
        '200':
          description: OK

components:
  schemas:
    IUserDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time
