global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: rust-web-app
    static_configs:
      - targets: ['rust-web-app:8080']

  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']